name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: pre task
      run: |
        cat ~/.ssh/id_ed25519.pub
        ls -la ~/.ssh
        ls -la

    - name: clone develop branche of integration repo
      run: | 
        git clone git@github.com:etn-electrical/etn-gwci-integrationtests.git -b develop
        cd ansible
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook Clean
      run: ansible-playbook clean-device-simulator-playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'

    - name: Run Ansible Playbook Deploy
      run: ansible-playbook deploy-device-simulator-playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
