name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: pre task
      run: |
        ls -la
        ls -la ~/.ssh
        pwd

    - name: clone develop branche of integration repo
      run: | 
        git clone https://franklinfokodjomou-eaton:${{ secrets.TOKEN }}@github.com/etn-electrical/etn-gwci-integrationtests.git -b develop
        cd etn-gwci-integrationtests/ansible

    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook Clean
      run: ansible-playbook clean-device-simulator-playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'

    - name: Run Ansible Playbook Deploy
      run: ansible-playbook deploy-device-simulator-playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
